### ISSUE TITLE
Help with getting an object from within an object.

### ISSUE THREAD

**Issue by jenkaplan** [jenkaplan/Project2GA#1]
CONTEXT

WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "User views the top stories"

WHAT YOU ARE TRYING TO DO:
I am trying to get the stories to render onto the page.

DETAILED DESCRIPTION OF THE BUG/ERROR:
I have an object within an object. I am trying to access the title, abstract, and URL from within that second object. 

WHAT I'VE TRIED
Well there is no error message as everything is loading as I am telling it to. I worked on it with Alex and we determined that there is an object within an object that I somehow need to get access to. He wasn't sure how to do it. I did some googling and maybe I need to use .filter, but I'm not sure how to use it either.

QUESTION
Can you help me get the properties from the object within the object?

@thoughtbyte

**Comment by thoughtbyte** [comment]
good job!
